name: bloc_template
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  go_router: ^12.1.3
  intl: ^0.18.1
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  intl_utils: ^2.8.5


flutter:
  uses-material-design: true
  generate: true

  assets:
      - assets/images/
      - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: en
  output_dir: lib/l10n/generated
  arb_dir: lib/l10n